# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 04:00
from __future__ import unicode_literals
from ..models import Aspect
from django.db import migrations
import csv
import os


def load_aspects_from_csv(apps, schema_editor):
    f_name = os.path.join(os.path.dirname(__file__), 'data/aspects.csv')
    with open(f_name) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            name = row['name']
            description = row['description']
            new_aspect = Aspect(name=name, description=description)
            new_aspect.save()


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_aspects_from_csv),

    ]
