# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0002_auto_20180112_0400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIntakeQuiz',
            new_name='UserIntakeQuestion',
        ),
    ]
